name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Prepare
        run: sudo apt install -y coreutils quilt parted debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc kpartx gpg pigz qemu-utils

      - name: Build
        run: sudo bash build.sh -c config
      
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: MirrorOS
          path: deploy/*.img.gz
          if-no-files-found: error
